### ISSUE TITLE
There are error when i get source

### ISSUE THREAD

**Issue by thanhngch** [drgrib/ttimer#1]
go get github.com/drgrib/ttimer
# github.com/drgrib/ttimer/agent
../../go/src/github.com/drgrib/ttimer/agent/agent.go:110:10: undefined: termui.NewPar
../../go/src/github.com/drgrib/ttimer/agent/agent.go:111:21: undefined: termui.ColorDefault
../../go/src/github.com/drgrib/ttimer/agent/agent.go:115:15: undefined: termui.TermWidth
../../go/src/github.com/drgrib/ttimer/agent/agent.go:116:16: undefined: termui.TermHeight
../../go/src/github.com/drgrib/ttimer/agent/agent.go:132:2: undefined: termui.Merge
../../go/src/github.com/drgrib/ttimer/agent/agent.go:132:20: undefined: termui.NewTimerCh
../../go/src/github.com/drgrib/ttimer/agent/agent.go:134:2: undefined: termui.Handle
../../go/src/github.com/drgrib/ttimer/agent/agent.go:135:12: e.Data undefined (type termui.Event has no field or method Data)
../../go/src/github.com/drgrib/ttimer/agent/agent.go:140:2: undefined: termui.Handle
../../go/src/github.com/drgrib/ttimer/agent/agent.go:141:16: undefined: termui.TermWidth
../../go/src/github.com/drgrib/ttimer/agent/agent.go:141:16: too many errors

**Comment by drgrib** [comment]
@thanhngch 
You are missing the `termui` dependency on your system. You can solve this using `dep` or by calling:

```
go get https://github.com/gizak/termui
```
