### ISSUE TITLE
Inlining functionality?

### ISSUE THREAD

**Issue by siennathesane** [drgrib/ttimer#6]
I'd like to inline `ttimer 30s` in a shell script, something like this:

```
#! /bin/zsh

echo "Starting a thing, will take 30s..."
ttimer 30s
```

And have this be an expected output:

```
$ ./timer.sh
Starting a thing, will take 30s...

# inlines the countdown
30s
```

Instead of this:

```
$ ./timer.sh
Starting a thing, will take 30s...

# takes over TTY
== 30s Timer ==
30s
```

Not a deal breaker, but would be nice to have. :)

**Comment by drgrib** [comment]
So are you saying you would like the timer to not go full-screen and still have any info that you `echo` before calling it visible as it counts down? Or just to not have the `== 30s Timer ==` header?

I have no idea if the former is even possible with the display library I use. I've never seen an example where it combines input from other scripts. The only examples I've seen are full-screen displays.

The latter is possible.

**Comment by drgrib** [comment]
Closing due to unclear request.
